name: Release
run-name: Release ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the app
        run: pnpm run tauri build

      - name: Create package (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          mkdir release
          cp src-tauri/target/release/bundle/appimage/*.AppImage release
          cp LICENSE.txt release
          cp -r static/. release
          cd release
          tar -czvf ../dosbox-express_${{ github.ref_name }}_linux.tar.gz *

      - name: Create package (windows only)
        if: matrix.platform == 'windows-2022'
        run: |
          mkdir release
          copy "src-tauri\target\release\dosbox-express.exe" release
          copy LICENSE.txt release
          xcopy /s static release
          Compress-Archive release\* dosbox-express_${{ github.ref_name }}_windows.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: |
            dosbox-express_${{ github.ref_name }}_linux.tar.gz
            dosbox-express_${{ github.ref_name }}_windows.zip
